AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'
    - 'config/initializers/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'